language: go

os:
  - linux
  - osx

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - "1.10.x"
  - tip

matrix:
    exclude:
        - os: osx
          go: 1.5.x
        - os: osx
          go: 1.6.x

before_install:
  - if [[ $TRAVIS_GO_VERSION == 1.9* ]]; then go get github.com/axw/gocov/gocov github.com/mattn/goveralls; fi

script:
  - while true; do echo "..."; sleep 60; done &
  - go test -v -tags ci -timeout 1h ./...
  - if [[ $TRAVIS_GO_VERSION == 1.9* ]]; then $GOPATH/bin/goveralls -service=travis-ci -ignore="examples/tokens/tokens.go,examples/space/space.go"; fi

notifications:
  email:
    on_success: change
    on_failure: always
